#macro ms_to_s 0.000001
#macro ms_to_s_60 0.00006
#macro s_to_ms 1000000
#macro s_to_ms_60 60000000
#macro fade_depth -16000
#macro bottom_depth -16000
#macro distance_far 999999
#macro max_players 2
//game modes
#macro gamemode_adventure 0
#macro gamemode_endless 1
#macro gamemode_storm 2
//character choice
#macro char_random 99
#macro char_rider 7
#macro char_ass 6
#macro char_punny 5
#macro char_biu 4
#macro char_raff 3
#macro char_pinky 2
#macro char_jimmy 1
//animation type
#macro an_loop 1
#macro an_clamp 2
#macro an_clamp_forever 3
//factions
#macro f_player 0
#macro f_enemy 1
#macro f_all 2
//ammo types
#macro type_light 0
#macro type_medium 1
#macro type_heavy 2
#macro type_grenade 3
#macro type_enemy 4
//colors
#macro K_BETU_RED make_color_rgb(178,0,65)
#macro K_BETU_GREEN2 make_color_rgb(99,210,0)
#macro K_BETU_GREEN make_color_rgb(0,178,45)
#macro K_BETU_BLUE make_color_rgb(0,88,178)
#macro K_BETU_ORANGE make_color_rgb(255,94,0)
#macro K_BETU_YELLOW make_color_rgb(244,246,0)
#macro K_BETU_MAGENTA_PAUSE make_color_rgb(255,26,96)
#macro K_BETU_MAGENTA make_colour_rgb(239,4,68)
//auto aim options
#macro K_AUTOAIM_OFF 0
#macro K_AUTOAIM_ASSIST 1
#macro K_AUTOAIM_FULL 2
//projectie types
#macro K_PROJECTILE_BASIC 0
#macro K_PROJECTILE_FLAME 1
#macro K_PROJECTILE_ROCKET 2
#macro K_PROJECTILE_SONIC 3
//input options
#macro K_INPUT_KEYBOARD 4
#macro K_INPUT_JOYSTICK1 0
#macro K_INPUT_JOYSTICK2 1
#macro K_INPUT_ALL 9
//languages
#macro lang_english 1
#macro lang_ptbr 2
#macro lang_huebr 3
#macro lang_russian 4
#macro lang_japanese 5
#macro lang_german 6
#macro lang_french 7
#macro lang_spanish 8
#macro lang_czech 9
#macro lang_korean 10
#macro lang_dutch 11
#macro lang_italian 12
#macro lang_chineseTr 13
#macro lang_chineseSp 14
#macro lang_indonesian 15
#macro lang_polish 16
#macro lang_hungary 17
#macro lang_thai 18
#macro lang_norwegian 19
#macro lang_danish 20
#macro lang_roumanian 21
#macro lang_pirate 22
#macro lang_hebrew 23
#macro lang_swedish 24
#macro lang_greek 25
#macro lang_vietnam 26
#macro lang_turkish 27
#macro lang_arabic 28
#macro lang_ptpt 29
#macro lang_suomi 30
//object pools
#macro blood_pool 0
#macro casing_pool 1
#macro pool_count 2
// events
#macro EVENT_INSTANCE_REMOVED "instance_removed"
// item rarity
#macro K_RARITY_COMMON 0
#macro K_COLOR_COMMON make_color_rgb(255,255,255)
#macro K_RARITY_UNCOMMON 1
#macro K_COLOR_UNCOMMON make_color_rgb(0,178,77)
#macro K_RARITY_RARE 2
#macro K_COLOR_RARE make_color_rgb(45,116,255)
#macro K_RARITY_EPIC 3
#macro K_COLOR_EPIC make_color_rgb(144,18,233)
#macro K_RARITY_LEGENDARY 4
#macro K_COLOR_LEGENDARY make_color_rgb(255,74,100)
#macro K_RARITY_SHOTGUN 1
#macro K_RARITY_SHOTGUN_CRUDE 0
#macro K_RARITY_SAWEDOFF 1
#macro K_RARITY_KEYTAR 4
#macro K_RARITY_SHOTGUN_HEAVY 3
#macro K_RARITY_SHOTGUN_RELIC 4
#macro K_RARITY_KAMILAUNCHER 4
#macro K_RARITY_ROCKETLAUNCHER 3
#macro K_RARITY_ROCKETLAUNCHER_RELIC 4
#macro K_RARITY_FLAMETHROWER 4
#macro K_RARITY_FLAKCANNON 2
#macro K_RARITY_RELICCANNON 4
#macro K_RARITY_BOSSGUN 4
#macro K_RARITY_GLOVES 4
#macro K_RARITY_BUCKLER 4
#macro K_RARITY_SPOOKYPISTOL 3
#macro K_RARITY_SPOOKYREAPER 3
#macro K_RARITY_SPOOKYBEAMER 3
#macro K_RARITY_PISTOL_ASSAULT 1
#macro K_RARITY_PISTOL_BOUNCER 2
#macro K_RARITY_PISTOL_PLASMA 2
#macro K_RARITY_PISTOL 0
#macro K_RARITY_PISTOL_HEAVY 1
#macro K_RARITY_PISTOL_RELIC 4
#macro K_RARITY_PISTOL_JIMMY 2
#macro K_RARITY_PISTOL_BLAST 2
#macro K_RARITY_SNIPER_RIFLE 2
#macro K_RARITY_SNIPER_RELIC 4
#macro K_RARITY_SNIPER_GHOST 4
#macro K_RARITY_ASSAULT_RIFLE 2
#macro K_RARITY_MINIGUN 2
#macro K_RARITY_MINIGUN_RELIC 4
#macro K_RARITY_DUCAN_RIFLE 4
#macro K_RARITY_DUCAN_SHOTGUN 4
#macro K_RARITY_DUCAN_PLASMA 4
#macro K_RARITY_RIFLE_RELIC 4
#macro K_RARITY_ASSAULT_RIFLE_CRUDE 0
#macro K_RARITY_BLITZ 2
#macro K_RARITY_SUBMACHINEGUN 1
#macro K_RARITY_SMG_RELIC 4
#macro K_RARITY_SMG_CRUDE 0
#macro K_RARITY_SMG_PLASMA 3
#macro K_RARITY_MACHINEGUN 2
#macro K_RARITY_HIGHMAG 2
#macro K_RARITY_BOUNCER 2

#macro K_RARITY_ALCOHOLIC_CARROT 0
#macro K_RARITY_PINEAPPLE_PUDDING 0
#macro K_RARITY_WATCHFUL_EYE 0
#macro K_RARITY_INFINITY_BATTERY 0
#macro K_RARITY_RABBIT_FOOT 0
#macro K_RARITY_MEGA_QUANTUM_CHIP 0
#macro K_RARITY_BLACK_CAT 0
#macro K_RARITY_YOTTABYTE_DRIVE 1
#macro K_RARITY_MIDNIGHT_BEER 1
#macro K_RARITY_MULTITOOL 1
#macro K_RARITY_ACTUAL_CARROT 1
#macro K_RARITY_MORNING_STAR 1
#macro K_RARITY_PINEAPPLE_PIE 1
#macro K_RARITY_FIRE_FREAK 2
#macro K_RARITY_MIDNIGHT_MEAL 2
#macro K_RARITY_YOTTABYTE_PROCESSOR 2
#macro K_RARITY_SHELL_CANDY 2
#macro K_RARITY_RABBIT_EARS 2
#macro K_RARITY_PURPLE_JUICE 3
#macro K_RARITY_PURE_SAND 3
#macro K_RARITY_LOAF_OF_BREAD 3
#macro K_RARITY_BLOOD_MOON 3
#macro K_RARITY_DEV_POTION 3
#macro K_RARITY_CRYSTAL_BACON 3

// Relic Definitions
#macro K_RELIC_ALCOHOLIC_CARROT 0
#macro K_RELIC_PINEAPPLE_PUDDING 1
#macro K_RELIC_YOTTABYTE_DRIVE 2
#macro K_RELIC_INFINITY_BATTERY 3
#macro K_RELIC_CRYSTAL_BACON 4
#macro K_RELIC_MIDNIGHT_BEER 5
#macro K_RELIC_WATCHFUL_EYE 6
#macro K_RELIC_DEV_POTION 7
#macro K_RELIC_MORNING_STAR 8
#macro K_RELIC_PINEAPPLE_PIE 9
#macro K_RELIC_RABBIT_FOOT 10
#macro K_RELIC_MIDNIGHT_MEAL 11
#macro K_RELIC_YOTTABYTE_PROCESSOR 12
#macro K_RELIC_MEGA_QUANTUM_CHIP 13
#macro K_RELIC_SHELL_CANDY 14
#macro K_RELIC_PURPLE_JUICE 15
#macro K_RELIC_RABBIT_EARS 16
#macro K_RELIC_PURE_SAND 17
#macro K_RELIC_LOAF_OF_BREAD 18
#macro K_RELIC_BLOOD_MOON 19
#macro K_RELIC_BLACK_CAT 20
#macro K_RELIC_MULTITOOL 21
#macro K_RELIC_ACTUAL_CARROT 22
#macro K_RELIC_FIRE_FREAK 23

// Difficulty Definitions
#macro K_DIFFICULTY_VERY_EASY 0
#macro K_DIFFICULTY_EASY 1
#macro K_DIFFICULTY_REGULAR 2
#macro K_DIFFICULTY_HARD 3
#macro K_DIFFICULTY_VERY_HARD 4
#macro K_DIFFICULTY_EXTREME 5
#macro K_DIFFICULTY_VERY_EXTREME 6
#macro K_DIFFICULTY_LEGENDARY 7
#macro K_DIFFICULTY_ASCENDANT 8