// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // controller_bootstrap
global.__objectDepths[1] = -16000; // controller_shadow_tall
global.__objectDepths[2] = 0; // controller_splashZueira
global.__objectDepths[3] = 0; // controller_camera
global.__objectDepths[4] = 100; // controller_pause
global.__objectDepths[5] = 0; // class_dataObject
global.__objectDepths[6] = 16000; // controller_effects
global.__objectDepths[7] = 0; // controller_end
global.__objectDepths[8] = -16000; // controller_steamAsync
global.__objectDepths[9] = 0; // class_lightsource
global.__objectDepths[10] = 0; // controller_splash
global.__objectDepths[11] = -16000; // controller_menu_main
global.__objectDepths[12] = 16000; // controller_menu_background
global.__objectDepths[13] = 999; // controller_intro
global.__objectDepths[14] = -16000; // controller_menuButtons
global.__objectDepths[15] = -16000; // controller_main
global.__objectDepths[16] = 0; // data_enemies
global.__objectDepths[17] = 0; // faction_player
global.__objectDepths[18] = 0; // data_enemiesEndless
global.__objectDepths[19] = 0; // data_chestItems
global.__objectDepths[20] = 0; // data_shopEndless
global.__objectDepths[21] = 0; // data_itemsEndless
global.__objectDepths[22] = 0; // class_player
global.__objectDepths[23] = 0; // class_gun
global.__objectDepths[24] = 0; // data_items
global.__objectDepths[25] = 0; // data_shop
global.__objectDepths[26] = 0; // class_melee
global.__objectDepths[27] = 0; // class_weapon
global.__objectDepths[28] = 0; // obj_pinky
global.__objectDepths[29] = 200; // obj_jimmy
global.__objectDepths[30] = 0; // fx_corpse_player
global.__objectDepths[31] = 0; // obj_rider
global.__objectDepths[32] = 0; // obj_assault_rifle
global.__objectDepths[33] = 0; // obj_assault_rifle_crude
global.__objectDepths[34] = 0; // obj_ducanShotgun
global.__objectDepths[35] = 0; // obj_assPlayer
global.__objectDepths[36] = 0; // obj_ducanRifle
global.__objectDepths[37] = 0; // obj_bouncer
global.__objectDepths[38] = 0; // obj_bossGun
global.__objectDepths[39] = 0; // obj_blitz
global.__objectDepths[40] = 0; // obj_ducanPlasma
global.__objectDepths[41] = 0; // obj_biu
global.__objectDepths[42] = 0; // obj_raff
global.__objectDepths[43] = 0; // obj_shield_biu
global.__objectDepths[44] = 0; // fx_melee_arc
global.__objectDepths[45] = 0; // obj_punny
global.__objectDepths[46] = 0; // obj_flamethrower
global.__objectDepths[47] = 0; // obj_flakCannon
global.__objectDepths[48] = 0; // obj_minigun_relic
global.__objectDepths[49] = 0; // obj_minigun
global.__objectDepths[50] = 0; // obj_pistol_relic
global.__objectDepths[51] = 0; // obj_keytar
global.__objectDepths[52] = 0; // obj_rocketlauncher
global.__objectDepths[53] = 0; // obj_pistol_blast
global.__objectDepths[54] = 0; // obj_machinegun
global.__objectDepths[55] = 0; // obj_pistol_bouncer
global.__objectDepths[56] = 0; // obj_highmag
global.__objectDepths[57] = 0; // obj_pistol_jimmy
global.__objectDepths[58] = 0; // obj_pistol_heavy
global.__objectDepths[59] = 0; // obj_pistol_assault
global.__objectDepths[60] = 0; // obj_relicCannon
global.__objectDepths[61] = 0; // obj_pistol_plasma
global.__objectDepths[62] = 0; // obj_smg_crude
global.__objectDepths[63] = 0; // obj_pistol
global.__objectDepths[64] = 0; // obj_sawedoff
global.__objectDepths[65] = 0; // obj_shotgun
global.__objectDepths[66] = 0; // obj_shotgun_crude
global.__objectDepths[67] = 0; // obj_shotgun_heavy
global.__objectDepths[68] = 0; // obj_rocketlauncher_relic
global.__objectDepths[69] = 0; // obj_shotgun_relic
global.__objectDepths[70] = 0; // obj_kamilauncher
global.__objectDepths[71] = 0; // obj_smg_relic
global.__objectDepths[72] = 0; // obj_smg_plasma
global.__objectDepths[73] = 0; // faction_ducan
global.__objectDepths[74] = 0; // obj_sniper_ghost
global.__objectDepths[75] = 0; // obj_spookyPistol
global.__objectDepths[76] = 0; // obj_sniper_rifle
global.__objectDepths[77] = 0; // obj_duck1_submachinegun
global.__objectDepths[78] = 0; // obj_duck1
global.__objectDepths[79] = 0; // faction_monster
global.__objectDepths[80] = 0; // obj_sniper_relic
global.__objectDepths[81] = 0; // obj_duck2_shotgun
global.__objectDepths[82] = 0; // obj_duck2_submachinegun
global.__objectDepths[83] = 0; // obj_duck3
global.__objectDepths[84] = 0; // obj_turtle1
global.__objectDepths[85] = 0; // obj_gloves
global.__objectDepths[86] = 0; // obj_duck2_heavy
global.__objectDepths[87] = 0; // obj_spookyBeamer
global.__objectDepths[88] = 0; // obj_submachinegun
global.__objectDepths[89] = 0; // obj_spookyReaper
global.__objectDepths[90] = 0; // obj_duck3_rocket
global.__objectDepths[91] = 0; // obj_turtle2_shotgun
global.__objectDepths[92] = 0; // obj_turtle1_shotgun
global.__objectDepths[93] = 0; // obj_buckler
global.__objectDepths[94] = 0; // obj_turtle2_assaultpistol
global.__objectDepths[95] = 0; // obj_turtle2_submachinegun
global.__objectDepths[96] = 0; // obj_turtle3
global.__objectDepths[97] = 0; // obj_kamiAlly
global.__objectDepths[98] = 0; // obj_turtle3_plasma
global.__objectDepths[99] = 0; // obj_turtle3_sniper
global.__objectDepths[100] = 0; // obj_kamikazelite
global.__objectDepths[101] = 0; // obj_kamikaze1
global.__objectDepths[102] = 0; // obj_kamitank
global.__objectDepths[103] = -16000; // obj_kamikazelite_flying
global.__objectDepths[104] = 0; // obj_turtle2
global.__objectDepths[105] = 0; // obj_turtle1_pistoleer
global.__objectDepths[106] = 0; // obj_rifle_relic
global.__objectDepths[107] = 0; // obj_wormTurtle
global.__objectDepths[108] = 0; // obj_ducanElite_rifle
global.__objectDepths[109] = 0; // obj_zombieTurtlePistol
global.__objectDepths[110] = 0; // obj_zombieTurtle
global.__objectDepths[111] = 0; // obj_ducanElite_sniper
global.__objectDepths[112] = 0; // obj_ducanElite_plasma
global.__objectDepths[113] = 0; // obj_worm
global.__objectDepths[114] = 0; // obj_zombieTurtleReaper
global.__objectDepths[115] = 0; // obj_ducanElite_rocket
global.__objectDepths[116] = 0; // obj_pistol_enemy
global.__objectDepths[117] = 0; // obj_pistol_spooky_enemy
global.__objectDepths[118] = 0; // obj_ducanPlasma_enemy
global.__objectDepths[119] = 0; // obj_reaper_enemy
global.__objectDepths[120] = 0; // obj_pistol_plasma_enemy
global.__objectDepths[121] = 0; // obj_needler_enemy
global.__objectDepths[122] = 0; // obj_pistol_heavy_enemy
global.__objectDepths[123] = 0; // obj_ducanElite_shotgun
global.__objectDepths[124] = -10000; // obj_ghost_ducan
global.__objectDepths[125] = 0; // obj_ducanRifle_enemy
global.__objectDepths[126] = 0; // obj_shotgun_enemy
global.__objectDepths[127] = 0; // obj_rocketlauncher_enemy
global.__objectDepths[128] = 0; // obj_ducanRocket_enemy
global.__objectDepths[129] = 0; // obj_sniperrifle_enemy
global.__objectDepths[130] = 0; // obj_boss
global.__objectDepths[131] = 0; // obj_ducanSniper_enemy
global.__objectDepths[132] = 0; // obj_machinegun_enemy
global.__objectDepths[133] = 0; // obj_submachinegun_enemy
global.__objectDepths[134] = 0; // obj_assaultpistol_enemy
global.__objectDepths[135] = 0; // obj_ducanShotgun_enemy
global.__objectDepths[136] = 0; // obj_boss_spawner
global.__objectDepths[137] = 0; // obj_assaultrifle_boss
global.__objectDepths[138] = 0; // obj_assaultrifle_enemy
global.__objectDepths[139] = 0; // obj_rocketlauncher_boss
global.__objectDepths[140] = 0; // class_enemy
global.__objectDepths[141] = 0; // obj_turtle_dummy
global.__objectDepths[142] = 0; // class_enemy_zombieShooter
global.__objectDepths[143] = 0; // obj_turtle_dummy_immortal
global.__objectDepths[144] = 16000; // obj_limit
global.__objectDepths[145] = 0; // class_enemy_shooter
global.__objectDepths[146] = 0; // class_solid
global.__objectDepths[147] = 0; // class_enemy_kamitank
global.__objectDepths[148] = 16000; // obj_teleporter_1
global.__objectDepths[149] = 16000; // obj_teleporter_2
global.__objectDepths[150] = 0; // class_enemy_jumper
global.__objectDepths[151] = 0; // class_enemy_kamikaze
global.__objectDepths[152] = 0; // class_summon
global.__objectDepths[153] = 16000; // obj_teleporter
global.__objectDepths[154] = 0; // class_enemy_zombie
global.__objectDepths[155] = 0; // obj_tentacle1
global.__objectDepths[156] = 16000; // obj_wall
global.__objectDepths[157] = 0; // class_gun_enemy
global.__objectDepths[158] = 16000; // obj_wall_stage3
global.__objectDepths[159] = 16000; // obj_teleporter_3
global.__objectDepths[160] = 16000; // obj_wall_stage4
global.__objectDepths[161] = 16000; // obj_teleporter_tutorial
global.__objectDepths[162] = 0; // class_level_wall
global.__objectDepths[163] = -16000; // obj_spawn_topLeft
global.__objectDepths[164] = -16000; // obj_spawn_item
global.__objectDepths[165] = 16000; // obj_wall_stage1
global.__objectDepths[166] = 0; // fx_teleporter
global.__objectDepths[167] = -16000; // obj_spawn_player
global.__objectDepths[168] = 0; // class_roots
global.__objectDepths[169] = 16000; // obj_bigwindow
global.__objectDepths[170] = 0; // class_crate
global.__objectDepths[171] = 16000; // obj_redbarrel
global.__objectDepths[172] = 16000; // obj_crate
global.__objectDepths[173] = 16000; // obj_wall_halloween
global.__objectDepths[174] = 0; // class_redbarrel
global.__objectDepths[175] = 16000; // obj_barrel
global.__objectDepths[176] = 16000; // obj_pumpkin
global.__objectDepths[177] = -16000; // obj_spawn_enemy
global.__objectDepths[178] = 0; // obj_teleporter_spawn
global.__objectDepths[179] = -16000; // obj_spawn_botRight
global.__objectDepths[180] = 16000; // obj_teleporter_secret
global.__objectDepths[181] = 16000; // obj_wall_stage2
global.__objectDepths[182] = 16000; // obj_teleporter_haunted
global.__objectDepths[183] = 0; // obj_kami_kage
global.__objectDepths[184] = 16000; // obj_roots1
global.__objectDepths[185] = 15997; // obj_generator2
global.__objectDepths[186] = 15997; // obj_wonderwall2
global.__objectDepths[187] = 15997; // obj_wonderwall1
global.__objectDepths[188] = 15997; // obj_wonderwall3
global.__objectDepths[189] = 15997; // obj_generator1
global.__objectDepths[190] = 16000; // obj_roots2
global.__objectDepths[191] = 15997; // obj_longbox
global.__objectDepths[192] = 0; // obj_swap_pinky
global.__objectDepths[193] = 15997; // obj_generator3
global.__objectDepths[194] = 0; // class_character_swap
global.__objectDepths[195] = 0; // obj_swap_jimmy
global.__objectDepths[196] = 0; // class_tactical_target
global.__objectDepths[197] = 16000; // obj_roots3
global.__objectDepths[198] = 16000; // obj_roots4
global.__objectDepths[199] = 0; // obj_redbarrel_spawner
global.__objectDepths[200] = 15997; // class_generator
global.__objectDepths[201] = 0; // obj_swap_raff
global.__objectDepths[202] = 0; // obj_shop2
global.__objectDepths[203] = 0; // obj_swap_biu
global.__objectDepths[204] = 0; // obj_shop
global.__objectDepths[205] = 0; // fx_relic
global.__objectDepths[206] = 0; // obj_altar_players
global.__objectDepths[207] = 0; // obj_endlessUnlock
global.__objectDepths[208] = 0; // obj_altar_relic
global.__objectDepths[209] = 0; // obj_swap_punny
global.__objectDepths[210] = 0; // obj_swap_ass
global.__objectDepths[211] = -16000; // obj_endless_balloon
global.__objectDepths[212] = -16000; // obj_gunnar_balloon
global.__objectDepths[213] = -16000; // obj_sae_balloon
global.__objectDepths[214] = 0; // obj_ass
global.__objectDepths[215] = -16000; // obj_ass_balloon
global.__objectDepths[216] = 0; // class_fx_boxbreak
global.__objectDepths[217] = 16000; // obj_spikeTrap
global.__objectDepths[218] = -16000; // class_balloon
global.__objectDepths[219] = 16000; // obj_digSpot
global.__objectDepths[220] = 10; // fx_corpse
global.__objectDepths[221] = -100; // fx_detector
global.__objectDepths[222] = -16000; // fx_detectorArrow
global.__objectDepths[223] = 0; // class_bouncer
global.__objectDepths[224] = 10; // fx_corpse_boss
global.__objectDepths[225] = 0; // fx_ducanFlag
global.__objectDepths[226] = -16000; // fx_blood
global.__objectDepths[227] = 0; // fx_activation
global.__objectDepths[228] = -16000; // fx_damage
global.__objectDepths[229] = 0; // fx_barrel_break
global.__objectDepths[230] = 10; // fx_corpseRevive
global.__objectDepths[231] = 0; // fx_crate_break
global.__objectDepths[232] = 0; // fx_reviveZombie
global.__objectDepths[233] = 0; // fx_dirt
global.__objectDepths[234] = 0; // fx_death_generic
global.__objectDepths[235] = -16000; // fx_crate_particles
global.__objectDepths[236] = -16000; // fx_fadeFromBlack
global.__objectDepths[237] = 0; // fx_casing
global.__objectDepths[238] = -16000; // fx_worm
global.__objectDepths[239] = -16000; // fx_fadeToBlack
global.__objectDepths[240] = 0; // fx_bigMessage
global.__objectDepths[241] = -16000; // fx_digDirt
global.__objectDepths[242] = 0; // fx_kami_cageDestroy
global.__objectDepths[243] = 0; // fx_hit
global.__objectDepths[244] = 0; // fx_duck_dash
global.__objectDepths[245] = 10000; // fx_exitArrow
global.__objectDepths[246] = -16000; // fx_digItem
global.__objectDepths[247] = 0; // fx_longbox_break
global.__objectDepths[248] = 0; // fx_shield_down
global.__objectDepths[249] = 0; // fx_shield
global.__objectDepths[250] = 0; // fx_roots_break
global.__objectDepths[251] = -10000; // fx_shield_explosion
global.__objectDepths[252] = 0; // fx_sprint
global.__objectDepths[253] = -16000; // fx_skull
global.__objectDepths[254] = 0; // fx_explosion_mini
global.__objectDepths[255] = 0; // fx_kamikaze_dash
global.__objectDepths[256] = 0; // fx_pumpkin_break
global.__objectDepths[257] = 0; // fx_kamikaze_fly
global.__objectDepths[258] = 0; // fx_explosion_regular
global.__objectDepths[259] = 0; // fx_explosion_shield
global.__objectDepths[260] = 0; // fx_superShield
global.__objectDepths[261] = 0; // fx_shield_up
global.__objectDepths[262] = 16000; // fx_grenadeTarget
global.__objectDepths[263] = 0; // fx_player_dash
global.__objectDepths[264] = 0; // obj_grenadeNew
global.__objectDepths[265] = 0; // obj_grenadeSuperShield
global.__objectDepths[266] = 0; // fx_explosionKami
global.__objectDepths[267] = 0; // obj_grenadeKami
global.__objectDepths[268] = 0; // obj_grenade_enemyNew
global.__objectDepths[269] = 0; // class_grenadeNew
global.__objectDepths[270] = -16000; // class_gui_floaty
global.__objectDepths[271] = 0; // gui_dynamic_relic3
global.__objectDepths[272] = -16000; // gui_info
global.__objectDepths[273] = 0; // gui_dynamic_relic1
global.__objectDepths[274] = 0; // gui_dynamic_bounty
global.__objectDepths[275] = 0; // gui_dynamic_relic2
global.__objectDepths[276] = 0; // gui_dynamic_ammo1
global.__objectDepths[277] = 0; // class_gui_fader
global.__objectDepths[278] = 0; // class_gui_dynamic
global.__objectDepths[279] = 0; // gui_dynamic_ammo2
global.__objectDepths[280] = 0; // gui_logo
global.__objectDepths[281] = 0; // class_gui_dynamic_relic
global.__objectDepths[282] = -16000; // gui_reload_bar
global.__objectDepths[283] = -16000; // gui_dynamicBarEnemy
global.__objectDepths[284] = -16000; // fx_prompt_e
global.__objectDepths[285] = -16000; // fx_info_pickup
global.__objectDepths[286] = 0; // gui_intro_text
global.__objectDepths[287] = 0; // gui_weaponInfo
global.__objectDepths[288] = 0; // menu_char_rider
global.__objectDepths[289] = 0; // menu_char_jimmy
global.__objectDepths[290] = -16000; // gui_dynamicBar
global.__objectDepths[291] = 0; // gui_score
global.__objectDepths[292] = -16000; // gui_stage
global.__objectDepths[293] = 0; // class_menu_btnChar
global.__objectDepths[294] = 0; // gui_playerInfo
global.__objectDepths[295] = -16000; // gui_info_lowPerformance
global.__objectDepths[296] = 1000; // gui_credits_text
global.__objectDepths[297] = 200; // menu_fx_charBar
global.__objectDepths[298] = 0; // menu_char_pinky
global.__objectDepths[299] = 10; // menu_char_card1
global.__objectDepths[300] = 0; // menu_char_playerCard
global.__objectDepths[301] = 10; // menu_char_card2
global.__objectDepths[302] = 0; // menu_char_button
global.__objectDepths[303] = 0; // menu_char_random
global.__objectDepths[304] = 0; // menu_char_punny
global.__objectDepths[305] = 0; // menu_char_buttonOk
global.__objectDepths[306] = 0; // menu_char_biu
global.__objectDepths[307] = 0; // menu_char_ass
global.__objectDepths[308] = 0; // menu_char_raff
global.__objectDepths[309] = 0; // menu_char_buttonCancel
global.__objectDepths[310] = 0; // class_menu_button_toggle
global.__objectDepths[311] = 0; // menu_char_playerStat
global.__objectDepths[312] = 0; // menu_btn_endless
global.__objectDepths[313] = 50; // menu_char_inputBar
global.__objectDepths[314] = 0; // menu_btn_settings
global.__objectDepths[315] = 0; // class_menu_button_nav
global.__objectDepths[316] = 0; // class_menu_button
global.__objectDepths[317] = 0; // class_menu_button_main
global.__objectDepths[318] = 0; // menu_btn_daily
global.__objectDepths[319] = 0; // menu_btn_quit
global.__objectDepths[320] = 0; // menu_btn_credits
global.__objectDepths[321] = 5; // menu_btn_confirm_daily
global.__objectDepths[322] = 0; // menu_fx_rogue
global.__objectDepths[323] = 0; // menu_fx_mapping
global.__objectDepths[324] = 0; // menu_fx_pause
global.__objectDepths[325] = 0; // menu_fx_opensource
global.__objectDepths[326] = 0; // menu_fx_charSelection
global.__objectDepths[327] = 0; // menu_fx_twitter
global.__objectDepths[328] = 0; // menu_fx_facebook
global.__objectDepths[329] = -1; // menu_fx_dailyBanner
global.__objectDepths[330] = 0; // menu_fx_logo
global.__objectDepths[331] = 0; // menu_btn_cancel
global.__objectDepths[332] = 0; // menu_fx_forums
global.__objectDepths[333] = 0; // menu_statsBox
global.__objectDepths[334] = 0; // menu_fx_performance
global.__objectDepths[335] = 0; // menu_btn_play
global.__objectDepths[336] = 0; // menu_btn_confirm_nested
global.__objectDepths[337] = 0; // menu_btn_mapping
global.__objectDepths[338] = 0; // menu_btn_performance
global.__objectDepths[339] = 0; // menu_btn_confirm_delete
global.__objectDepths[340] = 0; // menu_fx_settings
global.__objectDepths[341] = 0; // menu_btn_delete
global.__objectDepths[342] = 0; // menu_fx_gameplay
global.__objectDepths[343] = 0; // menu_btn_master
global.__objectDepths[344] = 0; // menu_btn_sound
global.__objectDepths[345] = 0; // menu_btn_music
global.__objectDepths[346] = 0; // menu_btn_cancel_nested
global.__objectDepths[347] = 0; // menu_btn_confirm
global.__objectDepths[348] = 0; // menu_btn_gameplay
global.__objectDepths[349] = -99; // menu_btn_minus
global.__objectDepths[350] = 0; // menu_btn_screenshake
global.__objectDepths[351] = 0; // menu_btn_sticky
global.__objectDepths[352] = 0; // menu_btn_targeting
global.__objectDepths[353] = 0; // splash_fx_zueira
global.__objectDepths[354] = 0; // menu_btn_vibration
global.__objectDepths[355] = 0; // menu_btn_fullscreen
global.__objectDepths[356] = 0; // menu_btn_showammo
global.__objectDepths[357] = 0; // menu_btn_language
global.__objectDepths[358] = 0; // menu_btn_input
global.__objectDepths[359] = -99; // menu_btn_plus
global.__objectDepths[360] = 0; // menu_btn_doubletap
global.__objectDepths[361] = 0; // menu_btn_mwheel
global.__objectDepths[362] = 0; // menu_btn_persistent
global.__objectDepths[363] = 0; // class_menu_fx_keymap
global.__objectDepths[364] = 0; // menu_btn_reflections
global.__objectDepths[365] = 0; // menu_btn_friendlyfire
global.__objectDepths[366] = 0; // menu_btn_allowFreeze
global.__objectDepths[367] = 0; // menu_btn_resolution
global.__objectDepths[368] = 0; // menu_btn_moveup2
global.__objectDepths[369] = 0; // menu_btn_movedown
global.__objectDepths[370] = 0; // menu_btn_dynamics
global.__objectDepths[371] = 0; // menu_btn_moveright
global.__objectDepths[372] = 0; // menu_btn_movedown1
global.__objectDepths[373] = 0; // menu_btn_movedown2
global.__objectDepths[374] = 0; // menu_btn_mapping_default
global.__objectDepths[375] = 0; // menu_btn_moveright1
global.__objectDepths[376] = 0; // menu_btn_particles
global.__objectDepths[377] = 0; // menu_btn_moveright2
global.__objectDepths[378] = 0; // menu_btn_shadows
global.__objectDepths[379] = 0; // menu_btn_moveup
global.__objectDepths[380] = 0; // menu_btn_moveup1
global.__objectDepths[381] = 0; // menu_btn_fire2
global.__objectDepths[382] = 0; // menu_btn_aim1
global.__objectDepths[383] = 0; // menu_btn_aim2
global.__objectDepths[384] = 0; // class_button_remap
global.__objectDepths[385] = 0; // menu_btn_moveleft
global.__objectDepths[386] = 0; // menu_btn_melee
global.__objectDepths[387] = 0; // menu_btn_moveleft1
global.__objectDepths[388] = 0; // menu_btn_moveleft2
global.__objectDepths[389] = 0; // menu_btn_grenade1
global.__objectDepths[390] = 0; // menu_btn_melee1
global.__objectDepths[391] = 0; // menu_btn_melee2
global.__objectDepths[392] = 0; // menu_btn_sprint
global.__objectDepths[393] = 0; // menu_btn_use
global.__objectDepths[394] = 0; // menu_btn_fire1
global.__objectDepths[395] = 0; // menu_btn_use1
global.__objectDepths[396] = 0; // menu_btn_sprint1
global.__objectDepths[397] = 0; // menu_btn_sprint2
global.__objectDepths[398] = 0; // menu_btn_use2
global.__objectDepths[399] = 0; // menu_btn_switch2
global.__objectDepths[400] = 0; // menu_btn_switch1
global.__objectDepths[401] = 0; // menu_btn_fire
global.__objectDepths[402] = 0; // menu_btn_reload
global.__objectDepths[403] = 0; // menu_btn_switch
global.__objectDepths[404] = 0; // menu_btn_sprinttoggle1
global.__objectDepths[405] = 0; // menu_btn_sprinttoggle2
global.__objectDepths[406] = 0; // menu_btn_sprinttoggle
global.__objectDepths[407] = 0; // menu_btn_reload1
global.__objectDepths[408] = 0; // menu_btn_aim
global.__objectDepths[409] = 0; // menu_btn_grenade
global.__objectDepths[410] = 0; // menu_btn_reload2
global.__objectDepths[411] = 0; // menu_btn_grenade2
global.__objectDepths[412] = 0; // pausemenu_btn_ship
global.__objectDepths[413] = 0; // pausemenu_btn_exit
global.__objectDepths[414] = 0; // pausemenu_btn_continue
global.__objectDepths[415] = 0; // class_pickup_shield
global.__objectDepths[416] = -999999; // gui_badgeLoading
global.__objectDepths[417] = 0; // class_interactive_master
global.__objectDepths[418] = 0; // pausemenu_btn_menu
global.__objectDepths[419] = 0; // obj_pickup_candyLarge
global.__objectDepths[420] = 0; // obj_pickup_candy
global.__objectDepths[421] = 0; // obj_pickup_superShield
global.__objectDepths[422] = 0; // obj_pickup_health
global.__objectDepths[423] = 0; // obj_pickup_shield
global.__objectDepths[424] = 0; // obj_pickup_lightammo
global.__objectDepths[425] = 0; // obj_pickup_heavyammo
global.__objectDepths[426] = 0; // obj_pickup_healthBig
global.__objectDepths[427] = 0; // obj_pickup_mediumammo
global.__objectDepths[428] = 0; // obj_pickup_shotgun
global.__objectDepths[429] = 0; // class_pickup_weapon
global.__objectDepths[430] = 0; // obj_pickup_sawedoff
global.__objectDepths[431] = 0; // obj_pickup_grenade
global.__objectDepths[432] = 0; // obj_pickup_shotgun_relic
global.__objectDepths[433] = 0; // obj_pickup_kamilauncher
global.__objectDepths[434] = 0; // obj_pickup_shotgun_crude
global.__objectDepths[435] = 0; // obj_pickup_rocketlauncher_relic
global.__objectDepths[436] = 0; // obj_pickup_flamethrower
global.__objectDepths[437] = 0; // class_pickup_health
global.__objectDepths[438] = 0; // obj_pickup_keytar
global.__objectDepths[439] = 0; // obj_pickup_rocketlauncher
global.__objectDepths[440] = 0; // menu_fx_zoeira
global.__objectDepths[441] = 0; // obj_pickup_coin
global.__objectDepths[442] = 0; // obj_pickup_ammo
global.__objectDepths[443] = 0; // class_pickup_ammo
global.__objectDepths[444] = 0; // class_pickup_superShield
global.__objectDepths[445] = 0; // obj_pickup_shotgun_heavy
global.__objectDepths[446] = 0; // obj_pickup_spookyPistol
global.__objectDepths[447] = 0; // obj_pickup_buckler
global.__objectDepths[448] = 0; // obj_pickup_relicCannon
global.__objectDepths[449] = 0; // obj_pickup_gloves
global.__objectDepths[450] = 0; // obj_pickup_spookyReaper
global.__objectDepths[451] = 0; // obj_pickup_spooky_beamer
global.__objectDepths[452] = 0; // obj_pickup_pistol_heavy
global.__objectDepths[453] = 0; // obj_pickup_pistol_blast
global.__objectDepths[454] = 0; // obj_pickup_bossGun
global.__objectDepths[455] = 0; // obj_pickup_pistol_bouncer
global.__objectDepths[456] = 0; // obj_pickup_pistol_assault
global.__objectDepths[457] = 0; // obj_pickup_pistol_plasma
global.__objectDepths[458] = 0; // obj_pickup_sniper_rifle
global.__objectDepths[459] = 0; // obj_pickup_sniper_ghost
global.__objectDepths[460] = 0; // obj_pickup_sniper_relic
global.__objectDepths[461] = 0; // obj_pickup_assault_rifle
global.__objectDepths[462] = 0; // obj_pickup_minigun_relic
global.__objectDepths[463] = 0; // obj_pickup_ducan_shotgun
global.__objectDepths[464] = 0; // obj_pickup_ducan_plasma
global.__objectDepths[465] = 0; // obj_pickup_pistol
global.__objectDepths[466] = 0; // obj_pickup_assault_rifle_crude
global.__objectDepths[467] = 0; // obj_pickup_pistol_jimmy
global.__objectDepths[468] = 0; // obj_pickup_smg_relic
global.__objectDepths[469] = 0; // obj_pickup_submachinegun
global.__objectDepths[470] = 0; // obj_pickup_smg_crude
global.__objectDepths[471] = 0; // obj_pickup_smg_plasma
global.__objectDepths[472] = 0; // obj_pickup_machinegun
global.__objectDepths[473] = 0; // obj_pickup_pistol_relic
global.__objectDepths[474] = 0; // obj_pickup_flakCannon
global.__objectDepths[475] = 0; // obj_pickup_highmag
global.__objectDepths[476] = 0; // obj_pickup_bouncer
global.__objectDepths[477] = 0; // obj_pickup_ducan_rifle
global.__objectDepths[478] = 0; // obj_pickup_minigun
global.__objectDepths[479] = 0; // obj_pickup_rifle_relic
global.__objectDepths[480] = 0; // obj_pickup_blitz
global.__objectDepths[481] = 0; // class_projectile
global.__objectDepths[482] = -9999999; // obj_flame
global.__objectDepths[483] = 0; // obj_rocket_relic
global.__objectDepths[484] = -9999999; // obj_projectile_blast
global.__objectDepths[485] = 0; // obj_projectile_plasma
global.__objectDepths[486] = -9999999; // obj_projectile_beam
global.__objectDepths[487] = -99999; // obj_rocket
global.__objectDepths[488] = -999999999; // obj_projectile_skull
global.__objectDepths[489] = 0; // obj_rocket_homing
global.__objectDepths[490] = -999999999; // obj_projectile_skullEnemy
global.__objectDepths[491] = -999999999; // obj_sonicboom
global.__objectDepths[492] = -99999; // obj_redbarrel_projectile
global.__objectDepths[493] = 0; // obj_projectile_enemy
global.__objectDepths[494] = -99999; // obj_kamiRocket
global.__objectDepths[495] = -9999999; // obj_projectile_player
global.__objectDepths[496] = 0; // obj_projectile_homingEnemy
global.__objectDepths[497] = 0; // obj_projectile_flak
global.__objectDepths[498] = 0; // obj_projectile_plasmaEnemy
global.__objectDepths[499] = 0; // class_tutorial_animated
global.__objectDepths[500] = 0; // obj_projectile_flakRelic
global.__objectDepths[501] = 0; // class_tutorial_static
global.__objectDepths[502] = 0; // fx_tutorial0
global.__objectDepths[503] = 0; // fx_stage2
global.__objectDepths[504] = 0; // fx_tutorial5
global.__objectDepths[505] = 0; // fx_stage3
global.__objectDepths[506] = 0; // fx_tutorial7
global.__objectDepths[507] = 0; // fx_stage4
global.__objectDepths[508] = 0; // fx_tutorial8
global.__objectDepths[509] = 0; // fx_tutorial9
global.__objectDepths[510] = 0; // fx_tutorial1
global.__objectDepths[511] = 0; // fx_tutorial2
global.__objectDepths[512] = 0; // fx_tutorial3
global.__objectDepths[513] = 0; // fx_tutorial4
global.__objectDepths[514] = 0; // fx_tutorial11
global.__objectDepths[515] = 0; // obj_unlock_light1
global.__objectDepths[516] = 0; // obj_unlock_shotgun_heavy
global.__objectDepths[517] = 0; // obj_unlock_medium2
global.__objectDepths[518] = 0; // obj_unlock_medium1
global.__objectDepths[519] = 0; // obj_unlock_light2
global.__objectDepths[520] = 0; // fx_stage1
global.__objectDepths[521] = 0; // obj_unlock_heavy1
global.__objectDepths[522] = 0; // fx_tutorial6
global.__objectDepths[523] = 0; // obj_unlock_shield2
global.__objectDepths[524] = 0; // obj_unlock_shield1
global.__objectDepths[525] = 0; // obj_unlock_shotgun
global.__objectDepths[526] = 0; // fx_tutorial10
global.__objectDepths[527] = 0; // obj_unlock_heavy4
global.__objectDepths[528] = 0; // obj_unlock_heavy3
global.__objectDepths[529] = 0; // obj_unlock_heavy2
global.__objectDepths[530] = 0; // obj_unlock_grenades1
global.__objectDepths[531] = 0; // obj_unlock_grenades2
global.__objectDepths[532] = 0; // obj_unlock_rocketlauncher
global.__objectDepths[533] = 0; // obj_shop_shield1
global.__objectDepths[534] = 0; // obj_unlock_pistol_assault
global.__objectDepths[535] = 0; // obj_unlock_assault_rifle
global.__objectDepths[536] = 0; // obj_unlock_pistol_heavy
global.__objectDepths[537] = 0; // obj_unlock_pistol_plasma
global.__objectDepths[538] = 0; // class_shop_ammo
global.__objectDepths[539] = 0; // obj_unlock_submachinegun
global.__objectDepths[540] = 0; // obj_unlock_sniper_rifle
global.__objectDepths[541] = 0; // class_shop_weapon
global.__objectDepths[542] = 0; // obj_shop_slot
global.__objectDepths[543] = 0; // obj_shop_shield2
global.__objectDepths[544] = 0; // class_shop_shield
global.__objectDepths[545] = 0; // obj_unlock_grenades3
global.__objectDepths[546] = 0; // obj_unlock_highmag
global.__objectDepths[547] = 0; // obj_unlock_machinegun
global.__objectDepths[548] = 0; // obj_shop_light2
global.__objectDepths[549] = 0; // obj_shop_medium1
global.__objectDepths[550] = 0; // obj_shop_light1
global.__objectDepths[551] = 0; // obj_shop_medium2
global.__objectDepths[552] = 0; // obj_shop_grenades1
global.__objectDepths[553] = 0; // obj_shop_heavy2
global.__objectDepths[554] = 0; // obj_shop_heavy1
global.__objectDepths[555] = 0; // obj_shop_heavy3
global.__objectDepths[556] = 0; // obj_shop_heavy4
global.__objectDepths[557] = 0; // obj_shop_grenades2
global.__objectDepths[558] = 0; // obj_shop_pistol_heavy
global.__objectDepths[559] = 0; // obj_shop_shotgun
global.__objectDepths[560] = 0; // obj_shop_pistol_plasma
global.__objectDepths[561] = 0; // obj_shop_pistol_assault
global.__objectDepths[562] = 0; // obj_shop_grenades3
global.__objectDepths[563] = 0; // obj_shop_assault_rifle
global.__objectDepths[564] = 0; // obj_shop_machinegun
global.__objectDepths[565] = 0; // obj_shop_shotgun_heavy
global.__objectDepths[566] = 0; // obj_shop_sniper_rifle
global.__objectDepths[567] = 0; // obj_shop_pineapple1
global.__objectDepths[568] = 0; // obj_shop_pineapple3
global.__objectDepths[569] = 0; // obj_shop_alcoholic1
global.__objectDepths[570] = 0; // obj_shop_pineapple2
global.__objectDepths[571] = 0; // obj_shop_alcoholic2
global.__objectDepths[572] = 0; // obj_shop_highmag
global.__objectDepths[573] = 0; // obj_shop_crystal1
global.__objectDepths[574] = 0; // class_shop_relic
global.__objectDepths[575] = 0; // obj_shop_alcoholic3
global.__objectDepths[576] = 0; // obj_shop_crystal2
global.__objectDepths[577] = 0; // obj_shop_crystal3
global.__objectDepths[578] = 0; // obj_shop_infinity1
global.__objectDepths[579] = 0; // obj_shop_rocketlauncher
global.__objectDepths[580] = 0; // obj_shop_infinity2
global.__objectDepths[581] = 0; // class_relic
global.__objectDepths[582] = 0; // obj_shop_watchful1
global.__objectDepths[583] = 0; // obj_shop_watchful2
global.__objectDepths[584] = 0; // obj_shop_dev1
global.__objectDepths[585] = 0; // obj_shop_dev3
global.__objectDepths[586] = 0; // obj_shop_yottabyte1
global.__objectDepths[587] = 0; // obj_relicReset
global.__objectDepths[588] = 0; // obj_shop_yottabyte2
global.__objectDepths[589] = 0; // obj_shop_watchful3
global.__objectDepths[590] = 0; // obj_shop_dev2
global.__objectDepths[591] = 0; // obj_relic_alcoholic_carrot
global.__objectDepths[592] = 0; // obj_relic_crystal_bacon
global.__objectDepths[593] = 0; // obj_shop_infinity3
global.__objectDepths[594] = 0; // obj_relic_infinity_battery
global.__objectDepths[595] = 0; // obj_relic_dev_potion
global.__objectDepths[596] = 0; // obj_relic_watchful_eye
global.__objectDepths[597] = 0; // obj_relic_midnight_beer
global.__objectDepths[598] = 0; // obj_relic_yottabyte_drive
global.__objectDepths[599] = 0; // obj_shop_midnight1
global.__objectDepths[600] = 0; // obj_shop_midnight3
global.__objectDepths[601] = 0; // obj_relic_pineapple1
global.__objectDepths[602] = 0; // obj_shop_midnight2
global.__objectDepths[603] = 0; // obj_relic_pineapple_pie
global.__objectDepths[604] = 0; // obj_relic_yottabyte_processor
global.__objectDepths[605] = 0; // obj_relic_pineapple2
global.__objectDepths[606] = 0; // obj_shop_yottabyte3
global.__objectDepths[607] = 0; // obj_relic_midnight_meal
global.__objectDepths[608] = 0; // obj_relic_pineapple_pudding
global.__objectDepths[609] = 0; // obj_relic_morning_star
global.__objectDepths[610] = 0; // obj_relic_rabbit_foot
global.__objectDepths[611] = 0; // obj_relic_mega_quantum_chip
global.__objectDepths[612] = 0; // obj_shop_submachinegun
global.__objectDepths[613] = 0; // obj_relic_alcoholic1
global.__objectDepths[614] = 0; // obj_relic_pineapple3
global.__objectDepths[615] = 0; // obj_relic_alcoholic2
global.__objectDepths[616] = 0; // obj_relic_infinity3
global.__objectDepths[617] = 0; // obj_relic_midnight2
global.__objectDepths[618] = 0; // obj_relic_watchful2
global.__objectDepths[619] = 0; // obj_relic_watchful1
global.__objectDepths[620] = 0; // obj_relic_watchful3
global.__objectDepths[621] = 0; // obj_relic_midnight1
global.__objectDepths[622] = 0; // obj_relic_midnight3
global.__objectDepths[623] = 0; // obj_relic_crystal1
global.__objectDepths[624] = 0; // obj_relic_alcoholic3
global.__objectDepths[625] = 0; // obj_relic_crystal2
global.__objectDepths[626] = 0; // obj_relic_crystal3
global.__objectDepths[627] = 0; // obj_relic_infinity2
global.__objectDepths[628] = 0; // obj_relic_dev2
global.__objectDepths[629] = 0; // obj_relic_yottabyte2
global.__objectDepths[630] = 0; // obj_revival_hologram
global.__objectDepths[631] = 0; // obj_relic_yottabyte3
global.__objectDepths[632] = 0; // obj_relic_infinity1
global.__objectDepths[633] = 0; // obj_relic_yottabyte1
global.__objectDepths[634] = 0; // obj_relic_dev3
global.__objectDepths[635] = 0; // obj_relic_dev1
global.__objectDepths[636] = 0; // obj_slot_tiered3
global.__objectDepths[637] = 0; // obj_sae
global.__objectDepths[638] = 0; // obj_slot_resource
global.__objectDepths[639] = 0; // obj_hackTerminal1
global.__objectDepths[640] = 0; // obj_slot_tiered1
global.__objectDepths[641] = 0; // obj_slot_tiered2
global.__objectDepths[642] = 0; // class_hack
global.__objectDepths[643] = 0; // obj_gunnar
global.__objectDepths[644] = 0; // obj_shopReset
global.__objectDepths[645] = 0; // class_endShop_weapon
global.__objectDepths[646] = 0; // obj_hackTerminal2
global.__objectDepths[647] = 0; // class_endShop_relic
global.__objectDepths[648] = 0; // class_endShop_ammo
global.__objectDepths[649] = 0; // class_slot_tiered
global.__objectDepths[650] = 0; // class_endshop_tiered
global.__objectDepths[651] = 0; // class_endShop_resource
global.__objectDepths[652] = 0; // obj_endShop_ammoLight
global.__objectDepths[653] = 0; // obj_endShop_heavyShotgun
global.__objectDepths[654] = 0; // obj_endShop_ammoGrenades
global.__objectDepths[655] = 0; // obj_endShop_bouncerPistol
global.__objectDepths[656] = 0; // obj_endShop_blitz
global.__objectDepths[657] = 0; // obj_endShop_ammoHeavy
global.__objectDepths[658] = 0; // obj_endShop_blastPistol
global.__objectDepths[659] = 0; // obj_endShop_crudeAssaultRifle
global.__objectDepths[660] = 0; // obj_endShop_assaultRifle
global.__objectDepths[661] = 0; // obj_endShop_highmag
global.__objectDepths[662] = 0; // obj_endShop_bouncer
global.__objectDepths[663] = 0; // obj_endShop_health
global.__objectDepths[664] = 0; // obj_endShop_flakCannon
global.__objectDepths[665] = 0; // obj_endShop_kamilauncher
global.__objectDepths[666] = 0; // obj_endShop_minigun
global.__objectDepths[667] = 0; // obj_endShop_plasmaSMG
global.__objectDepths[668] = 0; // obj_endShop_relicPistol
global.__objectDepths[669] = 0; // obj_endShop_plasmaPistol
global.__objectDepths[670] = 0; // obj_endShop_relicRifle
global.__objectDepths[671] = 0; // obj_endShop_ammoMedium
global.__objectDepths[672] = 0; // obj_endShop_relicMinigun
global.__objectDepths[673] = 0; // obj_endShop_relicRocket
global.__objectDepths[674] = 0; // obj_endShop_assaultPistol
global.__objectDepths[675] = 0; // obj_endShop_relicSMG
global.__objectDepths[676] = 0; // obj_endShop_rocketLauncher
global.__objectDepths[677] = 0; // obj_endShop_relicShotgun
global.__objectDepths[678] = 0; // obj_endShop_sawedoff
global.__objectDepths[679] = 0; // obj_endShop_smg
global.__objectDepths[680] = 0; // obj_endShop_shotgun
global.__objectDepths[681] = 0; // obj_endShop_machinegun
global.__objectDepths[682] = 0; // obj_endShop_overshield
global.__objectDepths[683] = 0; // obj_endShop_sniperRifle
global.__objectDepths[684] = 0; // obj_endShop_devPotion
global.__objectDepths[685] = 0; // obj_endShop_crystalBacon
global.__objectDepths[686] = 0; // obj_endShop_midnightBeer
global.__objectDepths[687] = 0; // obj_endShop_infinityBattery
global.__objectDepths[688] = 0; // obj_endShop_heavyPistol
global.__objectDepths[689] = 0; // obj_endShop_pineapplePudding
global.__objectDepths[690] = 0; // obj_endShop_rabbitFoot
global.__objectDepths[691] = 0; // obj_endShop_watchfulEye
global.__objectDepths[692] = 0; // obj_endShop_yottabyteDrive
global.__objectDepths[693] = 0; // obj_endShop_yottabyteProcessor
global.__objectDepths[694] = 0; // obj_endShop_relicCannon
global.__objectDepths[695] = 0; // obj_endShop_relicSniper
global.__objectDepths[696] = 0; // fx_chestRegular
global.__objectDepths[697] = 0; // obj_endShop_alcoholicCarrot
global.__objectDepths[698] = 0; // obj_endShop_midnightMeal
global.__objectDepths[699] = 0; // class_treasureChest
global.__objectDepths[700] = 0; // fx_chestDucan
global.__objectDepths[701] = 0; // obj_endShop_morningStar
global.__objectDepths[702] = 0; // fx_chestHaunted
global.__objectDepths[703] = 0; // obj_endShop_megaQuantumChip
global.__objectDepths[704] = 0; // obj_endShop_pineapplePie
global.__objectDepths[705] = 0; // obj_chestRegular
global.__objectDepths[706] = 0; // obj_chestDucan
global.__objectDepths[707] = 0; // obj_chestHaunted
global.__objectDepths[708] = 0; // class_chestFX


global.__objectNames[0] = "controller_bootstrap";
global.__objectNames[1] = "controller_shadow_tall";
global.__objectNames[2] = "controller_splashZueira";
global.__objectNames[3] = "controller_camera";
global.__objectNames[4] = "controller_pause";
global.__objectNames[5] = "class_dataObject";
global.__objectNames[6] = "controller_effects";
global.__objectNames[7] = "controller_end";
global.__objectNames[8] = "controller_steamAsync";
global.__objectNames[9] = "class_lightsource";
global.__objectNames[10] = "controller_splash";
global.__objectNames[11] = "controller_menu_main";
global.__objectNames[12] = "controller_menu_background";
global.__objectNames[13] = "controller_intro";
global.__objectNames[14] = "controller_menuButtons";
global.__objectNames[15] = "controller_main";
global.__objectNames[16] = "data_enemies";
global.__objectNames[17] = "faction_player";
global.__objectNames[18] = "data_enemiesEndless";
global.__objectNames[19] = "data_chestItems";
global.__objectNames[20] = "data_shopEndless";
global.__objectNames[21] = "data_itemsEndless";
global.__objectNames[22] = "class_player";
global.__objectNames[23] = "class_gun";
global.__objectNames[24] = "data_items";
global.__objectNames[25] = "data_shop";
global.__objectNames[26] = "class_melee";
global.__objectNames[27] = "class_weapon";
global.__objectNames[28] = "obj_pinky";
global.__objectNames[29] = "obj_jimmy";
global.__objectNames[30] = "fx_corpse_player";
global.__objectNames[31] = "obj_rider";
global.__objectNames[32] = "obj_assault_rifle";
global.__objectNames[33] = "obj_assault_rifle_crude";
global.__objectNames[34] = "obj_ducanShotgun";
global.__objectNames[35] = "obj_assPlayer";
global.__objectNames[36] = "obj_ducanRifle";
global.__objectNames[37] = "obj_bouncer";
global.__objectNames[38] = "obj_bossGun";
global.__objectNames[39] = "obj_blitz";
global.__objectNames[40] = "obj_ducanPlasma";
global.__objectNames[41] = "obj_biu";
global.__objectNames[42] = "obj_raff";
global.__objectNames[43] = "obj_shield_biu";
global.__objectNames[44] = "fx_melee_arc";
global.__objectNames[45] = "obj_punny";
global.__objectNames[46] = "obj_flamethrower";
global.__objectNames[47] = "obj_flakCannon";
global.__objectNames[48] = "obj_minigun_relic";
global.__objectNames[49] = "obj_minigun";
global.__objectNames[50] = "obj_pistol_relic";
global.__objectNames[51] = "obj_keytar";
global.__objectNames[52] = "obj_rocketlauncher";
global.__objectNames[53] = "obj_pistol_blast";
global.__objectNames[54] = "obj_machinegun";
global.__objectNames[55] = "obj_pistol_bouncer";
global.__objectNames[56] = "obj_highmag";
global.__objectNames[57] = "obj_pistol_jimmy";
global.__objectNames[58] = "obj_pistol_heavy";
global.__objectNames[59] = "obj_pistol_assault";
global.__objectNames[60] = "obj_relicCannon";
global.__objectNames[61] = "obj_pistol_plasma";
global.__objectNames[62] = "obj_smg_crude";
global.__objectNames[63] = "obj_pistol";
global.__objectNames[64] = "obj_sawedoff";
global.__objectNames[65] = "obj_shotgun";
global.__objectNames[66] = "obj_shotgun_crude";
global.__objectNames[67] = "obj_shotgun_heavy";
global.__objectNames[68] = "obj_rocketlauncher_relic";
global.__objectNames[69] = "obj_shotgun_relic";
global.__objectNames[70] = "obj_kamilauncher";
global.__objectNames[71] = "obj_smg_relic";
global.__objectNames[72] = "obj_smg_plasma";
global.__objectNames[73] = "faction_ducan";
global.__objectNames[74] = "obj_sniper_ghost";
global.__objectNames[75] = "obj_spookyPistol";
global.__objectNames[76] = "obj_sniper_rifle";
global.__objectNames[77] = "obj_duck1_submachinegun";
global.__objectNames[78] = "obj_duck1";
global.__objectNames[79] = "faction_monster";
global.__objectNames[80] = "obj_sniper_relic";
global.__objectNames[81] = "obj_duck2_shotgun";
global.__objectNames[82] = "obj_duck2_submachinegun";
global.__objectNames[83] = "obj_duck3";
global.__objectNames[84] = "obj_turtle1";
global.__objectNames[85] = "obj_gloves";
global.__objectNames[86] = "obj_duck2_heavy";
global.__objectNames[87] = "obj_spookyBeamer";
global.__objectNames[88] = "obj_submachinegun";
global.__objectNames[89] = "obj_spookyReaper";
global.__objectNames[90] = "obj_duck3_rocket";
global.__objectNames[91] = "obj_turtle2_shotgun";
global.__objectNames[92] = "obj_turtle1_shotgun";
global.__objectNames[93] = "obj_buckler";
global.__objectNames[94] = "obj_turtle2_assaultpistol";
global.__objectNames[95] = "obj_turtle2_submachinegun";
global.__objectNames[96] = "obj_turtle3";
global.__objectNames[97] = "obj_kamiAlly";
global.__objectNames[98] = "obj_turtle3_plasma";
global.__objectNames[99] = "obj_turtle3_sniper";
global.__objectNames[100] = "obj_kamikazelite";
global.__objectNames[101] = "obj_kamikaze1";
global.__objectNames[102] = "obj_kamitank";
global.__objectNames[103] = "obj_kamikazelite_flying";
global.__objectNames[104] = "obj_turtle2";
global.__objectNames[105] = "obj_turtle1_pistoleer";
global.__objectNames[106] = "obj_rifle_relic";
global.__objectNames[107] = "obj_wormTurtle";
global.__objectNames[108] = "obj_ducanElite_rifle";
global.__objectNames[109] = "obj_zombieTurtlePistol";
global.__objectNames[110] = "obj_zombieTurtle";
global.__objectNames[111] = "obj_ducanElite_sniper";
global.__objectNames[112] = "obj_ducanElite_plasma";
global.__objectNames[113] = "obj_worm";
global.__objectNames[114] = "obj_zombieTurtleReaper";
global.__objectNames[115] = "obj_ducanElite_rocket";
global.__objectNames[116] = "obj_pistol_enemy";
global.__objectNames[117] = "obj_pistol_spooky_enemy";
global.__objectNames[118] = "obj_ducanPlasma_enemy";
global.__objectNames[119] = "obj_reaper_enemy";
global.__objectNames[120] = "obj_pistol_plasma_enemy";
global.__objectNames[121] = "obj_needler_enemy";
global.__objectNames[122] = "obj_pistol_heavy_enemy";
global.__objectNames[123] = "obj_ducanElite_shotgun";
global.__objectNames[124] = "obj_ghost_ducan";
global.__objectNames[125] = "obj_ducanRifle_enemy";
global.__objectNames[126] = "obj_shotgun_enemy";
global.__objectNames[127] = "obj_rocketlauncher_enemy";
global.__objectNames[128] = "obj_ducanRocket_enemy";
global.__objectNames[129] = "obj_sniperrifle_enemy";
global.__objectNames[130] = "obj_boss";
global.__objectNames[131] = "obj_ducanSniper_enemy";
global.__objectNames[132] = "obj_machinegun_enemy";
global.__objectNames[133] = "obj_submachinegun_enemy";
global.__objectNames[134] = "obj_assaultpistol_enemy";
global.__objectNames[135] = "obj_ducanShotgun_enemy";
global.__objectNames[136] = "obj_boss_spawner";
global.__objectNames[137] = "obj_assaultrifle_boss";
global.__objectNames[138] = "obj_assaultrifle_enemy";
global.__objectNames[139] = "obj_rocketlauncher_boss";
global.__objectNames[140] = "class_enemy";
global.__objectNames[141] = "obj_turtle_dummy";
global.__objectNames[142] = "class_enemy_zombieShooter";
global.__objectNames[143] = "obj_turtle_dummy_immortal";
global.__objectNames[144] = "obj_limit";
global.__objectNames[145] = "class_enemy_shooter";
global.__objectNames[146] = "class_solid";
global.__objectNames[147] = "class_enemy_kamitank";
global.__objectNames[148] = "obj_teleporter_1";
global.__objectNames[149] = "obj_teleporter_2";
global.__objectNames[150] = "class_enemy_jumper";
global.__objectNames[151] = "class_enemy_kamikaze";
global.__objectNames[152] = "class_summon";
global.__objectNames[153] = "obj_teleporter";
global.__objectNames[154] = "class_enemy_zombie";
global.__objectNames[155] = "obj_tentacle1";
global.__objectNames[156] = "obj_wall";
global.__objectNames[157] = "class_gun_enemy";
global.__objectNames[158] = "obj_wall_stage3";
global.__objectNames[159] = "obj_teleporter_3";
global.__objectNames[160] = "obj_wall_stage4";
global.__objectNames[161] = "obj_teleporter_tutorial";
global.__objectNames[162] = "class_level_wall";
global.__objectNames[163] = "obj_spawn_topLeft";
global.__objectNames[164] = "obj_spawn_item";
global.__objectNames[165] = "obj_wall_stage1";
global.__objectNames[166] = "fx_teleporter";
global.__objectNames[167] = "obj_spawn_player";
global.__objectNames[168] = "class_roots";
global.__objectNames[169] = "obj_bigwindow";
global.__objectNames[170] = "class_crate";
global.__objectNames[171] = "obj_redbarrel";
global.__objectNames[172] = "obj_crate";
global.__objectNames[173] = "obj_wall_halloween";
global.__objectNames[174] = "class_redbarrel";
global.__objectNames[175] = "obj_barrel";
global.__objectNames[176] = "obj_pumpkin";
global.__objectNames[177] = "obj_spawn_enemy";
global.__objectNames[178] = "obj_teleporter_spawn";
global.__objectNames[179] = "obj_spawn_botRight";
global.__objectNames[180] = "obj_teleporter_secret";
global.__objectNames[181] = "obj_wall_stage2";
global.__objectNames[182] = "obj_teleporter_haunted";
global.__objectNames[183] = "obj_kami_kage";
global.__objectNames[184] = "obj_roots1";
global.__objectNames[185] = "obj_generator2";
global.__objectNames[186] = "obj_wonderwall2";
global.__objectNames[187] = "obj_wonderwall1";
global.__objectNames[188] = "obj_wonderwall3";
global.__objectNames[189] = "obj_generator1";
global.__objectNames[190] = "obj_roots2";
global.__objectNames[191] = "obj_longbox";
global.__objectNames[192] = "obj_swap_pinky";
global.__objectNames[193] = "obj_generator3";
global.__objectNames[194] = "class_character_swap";
global.__objectNames[195] = "obj_swap_jimmy";
global.__objectNames[196] = "class_tactical_target";
global.__objectNames[197] = "obj_roots3";
global.__objectNames[198] = "obj_roots4";
global.__objectNames[199] = "obj_redbarrel_spawner";
global.__objectNames[200] = "class_generator";
global.__objectNames[201] = "obj_swap_raff";
global.__objectNames[202] = "obj_shop2";
global.__objectNames[203] = "obj_swap_biu";
global.__objectNames[204] = "obj_shop";
global.__objectNames[205] = "fx_relic";
global.__objectNames[206] = "obj_altar_players";
global.__objectNames[207] = "obj_endlessUnlock";
global.__objectNames[208] = "obj_altar_relic";
global.__objectNames[209] = "obj_swap_punny";
global.__objectNames[210] = "obj_swap_ass";
global.__objectNames[211] = "obj_endless_balloon";
global.__objectNames[212] = "obj_gunnar_balloon";
global.__objectNames[213] = "obj_sae_balloon";
global.__objectNames[214] = "obj_ass";
global.__objectNames[215] = "obj_ass_balloon";
global.__objectNames[216] = "class_fx_boxbreak";
global.__objectNames[217] = "obj_spikeTrap";
global.__objectNames[218] = "class_balloon";
global.__objectNames[219] = "obj_digSpot";
global.__objectNames[220] = "fx_corpse";
global.__objectNames[221] = "fx_detector";
global.__objectNames[222] = "fx_detectorArrow";
global.__objectNames[223] = "class_bouncer";
global.__objectNames[224] = "fx_corpse_boss";
global.__objectNames[225] = "fx_ducanFlag";
global.__objectNames[226] = "fx_blood";
global.__objectNames[227] = "fx_activation";
global.__objectNames[228] = "fx_damage";
global.__objectNames[229] = "fx_barrel_break";
global.__objectNames[230] = "fx_corpseRevive";
global.__objectNames[231] = "fx_crate_break";
global.__objectNames[232] = "fx_reviveZombie";
global.__objectNames[233] = "fx_dirt";
global.__objectNames[234] = "fx_death_generic";
global.__objectNames[235] = "fx_crate_particles";
global.__objectNames[236] = "fx_fadeFromBlack";
global.__objectNames[237] = "fx_casing";
global.__objectNames[238] = "fx_worm";
global.__objectNames[239] = "fx_fadeToBlack";
global.__objectNames[240] = "fx_bigMessage";
global.__objectNames[241] = "fx_digDirt";
global.__objectNames[242] = "fx_kami_cageDestroy";
global.__objectNames[243] = "fx_hit";
global.__objectNames[244] = "fx_duck_dash";
global.__objectNames[245] = "fx_exitArrow";
global.__objectNames[246] = "fx_digItem";
global.__objectNames[247] = "fx_longbox_break";
global.__objectNames[248] = "fx_shield_down";
global.__objectNames[249] = "fx_shield";
global.__objectNames[250] = "fx_roots_break";
global.__objectNames[251] = "fx_shield_explosion";
global.__objectNames[252] = "fx_sprint";
global.__objectNames[253] = "fx_skull";
global.__objectNames[254] = "fx_explosion_mini";
global.__objectNames[255] = "fx_kamikaze_dash";
global.__objectNames[256] = "fx_pumpkin_break";
global.__objectNames[257] = "fx_kamikaze_fly";
global.__objectNames[258] = "fx_explosion_regular";
global.__objectNames[259] = "fx_explosion_shield";
global.__objectNames[260] = "fx_superShield";
global.__objectNames[261] = "fx_shield_up";
global.__objectNames[262] = "fx_grenadeTarget";
global.__objectNames[263] = "fx_player_dash";
global.__objectNames[264] = "obj_grenadeNew";
global.__objectNames[265] = "obj_grenadeSuperShield";
global.__objectNames[266] = "fx_explosionKami";
global.__objectNames[267] = "obj_grenadeKami";
global.__objectNames[268] = "obj_grenade_enemyNew";
global.__objectNames[269] = "class_grenadeNew";
global.__objectNames[270] = "class_gui_floaty";
global.__objectNames[271] = "gui_dynamic_relic3";
global.__objectNames[272] = "gui_info";
global.__objectNames[273] = "gui_dynamic_relic1";
global.__objectNames[274] = "gui_dynamic_bounty";
global.__objectNames[275] = "gui_dynamic_relic2";
global.__objectNames[276] = "gui_dynamic_ammo1";
global.__objectNames[277] = "class_gui_fader";
global.__objectNames[278] = "class_gui_dynamic";
global.__objectNames[279] = "gui_dynamic_ammo2";
global.__objectNames[280] = "gui_logo";
global.__objectNames[281] = "class_gui_dynamic_relic";
global.__objectNames[282] = "gui_reload_bar";
global.__objectNames[283] = "gui_dynamicBarEnemy";
global.__objectNames[284] = "fx_prompt_e";
global.__objectNames[285] = "fx_info_pickup";
global.__objectNames[286] = "gui_intro_text";
global.__objectNames[287] = "gui_weaponInfo";
global.__objectNames[288] = "menu_char_rider";
global.__objectNames[289] = "menu_char_jimmy";
global.__objectNames[290] = "gui_dynamicBar";
global.__objectNames[291] = "gui_score";
global.__objectNames[292] = "gui_stage";
global.__objectNames[293] = "class_menu_btnChar";
global.__objectNames[294] = "gui_playerInfo";
global.__objectNames[295] = "gui_info_lowPerformance";
global.__objectNames[296] = "gui_credits_text";
global.__objectNames[297] = "menu_fx_charBar";
global.__objectNames[298] = "menu_char_pinky";
global.__objectNames[299] = "menu_char_card1";
global.__objectNames[300] = "menu_char_playerCard";
global.__objectNames[301] = "menu_char_card2";
global.__objectNames[302] = "menu_char_button";
global.__objectNames[303] = "menu_char_random";
global.__objectNames[304] = "menu_char_punny";
global.__objectNames[305] = "menu_char_buttonOk";
global.__objectNames[306] = "menu_char_biu";
global.__objectNames[307] = "menu_char_ass";
global.__objectNames[308] = "menu_char_raff";
global.__objectNames[309] = "menu_char_buttonCancel";
global.__objectNames[310] = "class_menu_button_toggle";
global.__objectNames[311] = "menu_char_playerStat";
global.__objectNames[312] = "menu_btn_endless";
global.__objectNames[313] = "menu_char_inputBar";
global.__objectNames[314] = "menu_btn_settings";
global.__objectNames[315] = "class_menu_button_nav";
global.__objectNames[316] = "class_menu_button";
global.__objectNames[317] = "class_menu_button_main";
global.__objectNames[318] = "menu_btn_daily";
global.__objectNames[319] = "menu_btn_quit";
global.__objectNames[320] = "menu_btn_credits";
global.__objectNames[321] = "menu_btn_confirm_daily";
global.__objectNames[322] = "menu_fx_rogue";
global.__objectNames[323] = "menu_fx_mapping";
global.__objectNames[324] = "menu_fx_pause";
global.__objectNames[325] = "menu_fx_opensource";
global.__objectNames[326] = "menu_fx_charSelection";
global.__objectNames[327] = "menu_fx_twitter";
global.__objectNames[328] = "menu_fx_facebook";
global.__objectNames[329] = "menu_fx_dailyBanner";
global.__objectNames[330] = "menu_fx_logo";
global.__objectNames[331] = "menu_btn_cancel";
global.__objectNames[332] = "menu_fx_forums";
global.__objectNames[333] = "menu_statsBox";
global.__objectNames[334] = "menu_fx_performance";
global.__objectNames[335] = "menu_btn_play";
global.__objectNames[336] = "menu_btn_confirm_nested";
global.__objectNames[337] = "menu_btn_mapping";
global.__objectNames[338] = "menu_btn_performance";
global.__objectNames[339] = "menu_btn_confirm_delete";
global.__objectNames[340] = "menu_fx_settings";
global.__objectNames[341] = "menu_btn_delete";
global.__objectNames[342] = "menu_fx_gameplay";
global.__objectNames[343] = "menu_btn_master";
global.__objectNames[344] = "menu_btn_sound";
global.__objectNames[345] = "menu_btn_music";
global.__objectNames[346] = "menu_btn_cancel_nested";
global.__objectNames[347] = "menu_btn_confirm";
global.__objectNames[348] = "menu_btn_gameplay";
global.__objectNames[349] = "menu_btn_minus";
global.__objectNames[350] = "menu_btn_screenshake";
global.__objectNames[351] = "menu_btn_sticky";
global.__objectNames[352] = "menu_btn_targeting";
global.__objectNames[353] = "splash_fx_zueira";
global.__objectNames[354] = "menu_btn_vibration";
global.__objectNames[355] = "menu_btn_fullscreen";
global.__objectNames[356] = "menu_btn_showammo";
global.__objectNames[357] = "menu_btn_language";
global.__objectNames[358] = "menu_btn_input";
global.__objectNames[359] = "menu_btn_plus";
global.__objectNames[360] = "menu_btn_doubletap";
global.__objectNames[361] = "menu_btn_mwheel";
global.__objectNames[362] = "menu_btn_persistent";
global.__objectNames[363] = "class_menu_fx_keymap";
global.__objectNames[364] = "menu_btn_reflections";
global.__objectNames[365] = "menu_btn_friendlyfire";
global.__objectNames[366] = "menu_btn_allowFreeze";
global.__objectNames[367] = "menu_btn_resolution";
global.__objectNames[368] = "menu_btn_moveup2";
global.__objectNames[369] = "menu_btn_movedown";
global.__objectNames[370] = "menu_btn_dynamics";
global.__objectNames[371] = "menu_btn_moveright";
global.__objectNames[372] = "menu_btn_movedown1";
global.__objectNames[373] = "menu_btn_movedown2";
global.__objectNames[374] = "menu_btn_mapping_default";
global.__objectNames[375] = "menu_btn_moveright1";
global.__objectNames[376] = "menu_btn_particles";
global.__objectNames[377] = "menu_btn_moveright2";
global.__objectNames[378] = "menu_btn_shadows";
global.__objectNames[379] = "menu_btn_moveup";
global.__objectNames[380] = "menu_btn_moveup1";
global.__objectNames[381] = "menu_btn_fire2";
global.__objectNames[382] = "menu_btn_aim1";
global.__objectNames[383] = "menu_btn_aim2";
global.__objectNames[384] = "class_button_remap";
global.__objectNames[385] = "menu_btn_moveleft";
global.__objectNames[386] = "menu_btn_melee";
global.__objectNames[387] = "menu_btn_moveleft1";
global.__objectNames[388] = "menu_btn_moveleft2";
global.__objectNames[389] = "menu_btn_grenade1";
global.__objectNames[390] = "menu_btn_melee1";
global.__objectNames[391] = "menu_btn_melee2";
global.__objectNames[392] = "menu_btn_sprint";
global.__objectNames[393] = "menu_btn_use";
global.__objectNames[394] = "menu_btn_fire1";
global.__objectNames[395] = "menu_btn_use1";
global.__objectNames[396] = "menu_btn_sprint1";
global.__objectNames[397] = "menu_btn_sprint2";
global.__objectNames[398] = "menu_btn_use2";
global.__objectNames[399] = "menu_btn_switch2";
global.__objectNames[400] = "menu_btn_switch1";
global.__objectNames[401] = "menu_btn_fire";
global.__objectNames[402] = "menu_btn_reload";
global.__objectNames[403] = "menu_btn_switch";
global.__objectNames[404] = "menu_btn_sprinttoggle1";
global.__objectNames[405] = "menu_btn_sprinttoggle2";
global.__objectNames[406] = "menu_btn_sprinttoggle";
global.__objectNames[407] = "menu_btn_reload1";
global.__objectNames[408] = "menu_btn_aim";
global.__objectNames[409] = "menu_btn_grenade";
global.__objectNames[410] = "menu_btn_reload2";
global.__objectNames[411] = "menu_btn_grenade2";
global.__objectNames[412] = "pausemenu_btn_ship";
global.__objectNames[413] = "pausemenu_btn_exit";
global.__objectNames[414] = "pausemenu_btn_continue";
global.__objectNames[415] = "class_pickup_shield";
global.__objectNames[416] = "gui_badgeLoading";
global.__objectNames[417] = "class_interactive_master";
global.__objectNames[418] = "pausemenu_btn_menu";
global.__objectNames[419] = "obj_pickup_candyLarge";
global.__objectNames[420] = "obj_pickup_candy";
global.__objectNames[421] = "obj_pickup_superShield";
global.__objectNames[422] = "obj_pickup_health";
global.__objectNames[423] = "obj_pickup_shield";
global.__objectNames[424] = "obj_pickup_lightammo";
global.__objectNames[425] = "obj_pickup_heavyammo";
global.__objectNames[426] = "obj_pickup_healthBig";
global.__objectNames[427] = "obj_pickup_mediumammo";
global.__objectNames[428] = "obj_pickup_shotgun";
global.__objectNames[429] = "class_pickup_weapon";
global.__objectNames[430] = "obj_pickup_sawedoff";
global.__objectNames[431] = "obj_pickup_grenade";
global.__objectNames[432] = "obj_pickup_shotgun_relic";
global.__objectNames[433] = "obj_pickup_kamilauncher";
global.__objectNames[434] = "obj_pickup_shotgun_crude";
global.__objectNames[435] = "obj_pickup_rocketlauncher_relic";
global.__objectNames[436] = "obj_pickup_flamethrower";
global.__objectNames[437] = "class_pickup_health";
global.__objectNames[438] = "obj_pickup_keytar";
global.__objectNames[439] = "obj_pickup_rocketlauncher";
global.__objectNames[440] = "menu_fx_zoeira";
global.__objectNames[441] = "obj_pickup_coin";
global.__objectNames[442] = "obj_pickup_ammo";
global.__objectNames[443] = "class_pickup_ammo";
global.__objectNames[444] = "class_pickup_superShield";
global.__objectNames[445] = "obj_pickup_shotgun_heavy";
global.__objectNames[446] = "obj_pickup_spookyPistol";
global.__objectNames[447] = "obj_pickup_buckler";
global.__objectNames[448] = "obj_pickup_relicCannon";
global.__objectNames[449] = "obj_pickup_gloves";
global.__objectNames[450] = "obj_pickup_spookyReaper";
global.__objectNames[451] = "obj_pickup_spooky_beamer";
global.__objectNames[452] = "obj_pickup_pistol_heavy";
global.__objectNames[453] = "obj_pickup_pistol_blast";
global.__objectNames[454] = "obj_pickup_bossGun";
global.__objectNames[455] = "obj_pickup_pistol_bouncer";
global.__objectNames[456] = "obj_pickup_pistol_assault";
global.__objectNames[457] = "obj_pickup_pistol_plasma";
global.__objectNames[458] = "obj_pickup_sniper_rifle";
global.__objectNames[459] = "obj_pickup_sniper_ghost";
global.__objectNames[460] = "obj_pickup_sniper_relic";
global.__objectNames[461] = "obj_pickup_assault_rifle";
global.__objectNames[462] = "obj_pickup_minigun_relic";
global.__objectNames[463] = "obj_pickup_ducan_shotgun";
global.__objectNames[464] = "obj_pickup_ducan_plasma";
global.__objectNames[465] = "obj_pickup_pistol";
global.__objectNames[466] = "obj_pickup_assault_rifle_crude";
global.__objectNames[467] = "obj_pickup_pistol_jimmy";
global.__objectNames[468] = "obj_pickup_smg_relic";
global.__objectNames[469] = "obj_pickup_submachinegun";
global.__objectNames[470] = "obj_pickup_smg_crude";
global.__objectNames[471] = "obj_pickup_smg_plasma";
global.__objectNames[472] = "obj_pickup_machinegun";
global.__objectNames[473] = "obj_pickup_pistol_relic";
global.__objectNames[474] = "obj_pickup_flakCannon";
global.__objectNames[475] = "obj_pickup_highmag";
global.__objectNames[476] = "obj_pickup_bouncer";
global.__objectNames[477] = "obj_pickup_ducan_rifle";
global.__objectNames[478] = "obj_pickup_minigun";
global.__objectNames[479] = "obj_pickup_rifle_relic";
global.__objectNames[480] = "obj_pickup_blitz";
global.__objectNames[481] = "class_projectile";
global.__objectNames[482] = "obj_flame";
global.__objectNames[483] = "obj_rocket_relic";
global.__objectNames[484] = "obj_projectile_blast";
global.__objectNames[485] = "obj_projectile_plasma";
global.__objectNames[486] = "obj_projectile_beam";
global.__objectNames[487] = "obj_rocket";
global.__objectNames[488] = "obj_projectile_skull";
global.__objectNames[489] = "obj_rocket_homing";
global.__objectNames[490] = "obj_projectile_skullEnemy";
global.__objectNames[491] = "obj_sonicboom";
global.__objectNames[492] = "obj_redbarrel_projectile";
global.__objectNames[493] = "obj_projectile_enemy";
global.__objectNames[494] = "obj_kamiRocket";
global.__objectNames[495] = "obj_projectile_player";
global.__objectNames[496] = "obj_projectile_homingEnemy";
global.__objectNames[497] = "obj_projectile_flak";
global.__objectNames[498] = "obj_projectile_plasmaEnemy";
global.__objectNames[499] = "class_tutorial_animated";
global.__objectNames[500] = "obj_projectile_flakRelic";
global.__objectNames[501] = "class_tutorial_static";
global.__objectNames[502] = "fx_tutorial0";
global.__objectNames[503] = "fx_stage2";
global.__objectNames[504] = "fx_tutorial5";
global.__objectNames[505] = "fx_stage3";
global.__objectNames[506] = "fx_tutorial7";
global.__objectNames[507] = "fx_stage4";
global.__objectNames[508] = "fx_tutorial8";
global.__objectNames[509] = "fx_tutorial9";
global.__objectNames[510] = "fx_tutorial1";
global.__objectNames[511] = "fx_tutorial2";
global.__objectNames[512] = "fx_tutorial3";
global.__objectNames[513] = "fx_tutorial4";
global.__objectNames[514] = "fx_tutorial11";
global.__objectNames[515] = "obj_unlock_light1";
global.__objectNames[516] = "obj_unlock_shotgun_heavy";
global.__objectNames[517] = "obj_unlock_medium2";
global.__objectNames[518] = "obj_unlock_medium1";
global.__objectNames[519] = "obj_unlock_light2";
global.__objectNames[520] = "fx_stage1";
global.__objectNames[521] = "obj_unlock_heavy1";
global.__objectNames[522] = "fx_tutorial6";
global.__objectNames[523] = "obj_unlock_shield2";
global.__objectNames[524] = "obj_unlock_shield1";
global.__objectNames[525] = "obj_unlock_shotgun";
global.__objectNames[526] = "fx_tutorial10";
global.__objectNames[527] = "obj_unlock_heavy4";
global.__objectNames[528] = "obj_unlock_heavy3";
global.__objectNames[529] = "obj_unlock_heavy2";
global.__objectNames[530] = "obj_unlock_grenades1";
global.__objectNames[531] = "obj_unlock_grenades2";
global.__objectNames[532] = "obj_unlock_rocketlauncher";
global.__objectNames[533] = "obj_shop_shield1";
global.__objectNames[534] = "obj_unlock_pistol_assault";
global.__objectNames[535] = "obj_unlock_assault_rifle";
global.__objectNames[536] = "obj_unlock_pistol_heavy";
global.__objectNames[537] = "obj_unlock_pistol_plasma";
global.__objectNames[538] = "class_shop_ammo";
global.__objectNames[539] = "obj_unlock_submachinegun";
global.__objectNames[540] = "obj_unlock_sniper_rifle";
global.__objectNames[541] = "class_shop_weapon";
global.__objectNames[542] = "obj_shop_slot";
global.__objectNames[543] = "obj_shop_shield2";
global.__objectNames[544] = "class_shop_shield";
global.__objectNames[545] = "obj_unlock_grenades3";
global.__objectNames[546] = "obj_unlock_highmag";
global.__objectNames[547] = "obj_unlock_machinegun";
global.__objectNames[548] = "obj_shop_light2";
global.__objectNames[549] = "obj_shop_medium1";
global.__objectNames[550] = "obj_shop_light1";
global.__objectNames[551] = "obj_shop_medium2";
global.__objectNames[552] = "obj_shop_grenades1";
global.__objectNames[553] = "obj_shop_heavy2";
global.__objectNames[554] = "obj_shop_heavy1";
global.__objectNames[555] = "obj_shop_heavy3";
global.__objectNames[556] = "obj_shop_heavy4";
global.__objectNames[557] = "obj_shop_grenades2";
global.__objectNames[558] = "obj_shop_pistol_heavy";
global.__objectNames[559] = "obj_shop_shotgun";
global.__objectNames[560] = "obj_shop_pistol_plasma";
global.__objectNames[561] = "obj_shop_pistol_assault";
global.__objectNames[562] = "obj_shop_grenades3";
global.__objectNames[563] = "obj_shop_assault_rifle";
global.__objectNames[564] = "obj_shop_machinegun";
global.__objectNames[565] = "obj_shop_shotgun_heavy";
global.__objectNames[566] = "obj_shop_sniper_rifle";
global.__objectNames[567] = "obj_shop_pineapple1";
global.__objectNames[568] = "obj_shop_pineapple3";
global.__objectNames[569] = "obj_shop_alcoholic1";
global.__objectNames[570] = "obj_shop_pineapple2";
global.__objectNames[571] = "obj_shop_alcoholic2";
global.__objectNames[572] = "obj_shop_highmag";
global.__objectNames[573] = "obj_shop_crystal1";
global.__objectNames[574] = "class_shop_relic";
global.__objectNames[575] = "obj_shop_alcoholic3";
global.__objectNames[576] = "obj_shop_crystal2";
global.__objectNames[577] = "obj_shop_crystal3";
global.__objectNames[578] = "obj_shop_infinity1";
global.__objectNames[579] = "obj_shop_rocketlauncher";
global.__objectNames[580] = "obj_shop_infinity2";
global.__objectNames[581] = "class_relic";
global.__objectNames[582] = "obj_shop_watchful1";
global.__objectNames[583] = "obj_shop_watchful2";
global.__objectNames[584] = "obj_shop_dev1";
global.__objectNames[585] = "obj_shop_dev3";
global.__objectNames[586] = "obj_shop_yottabyte1";
global.__objectNames[587] = "obj_relicReset";
global.__objectNames[588] = "obj_shop_yottabyte2";
global.__objectNames[589] = "obj_shop_watchful3";
global.__objectNames[590] = "obj_shop_dev2";
global.__objectNames[591] = "obj_relic_alcoholic_carrot";
global.__objectNames[592] = "obj_relic_crystal_bacon";
global.__objectNames[593] = "obj_shop_infinity3";
global.__objectNames[594] = "obj_relic_infinity_battery";
global.__objectNames[595] = "obj_relic_dev_potion";
global.__objectNames[596] = "obj_relic_watchful_eye";
global.__objectNames[597] = "obj_relic_midnight_beer";
global.__objectNames[598] = "obj_relic_yottabyte_drive";
global.__objectNames[599] = "obj_shop_midnight1";
global.__objectNames[600] = "obj_shop_midnight3";
global.__objectNames[601] = "obj_relic_pineapple1";
global.__objectNames[602] = "obj_shop_midnight2";
global.__objectNames[603] = "obj_relic_pineapple_pie";
global.__objectNames[604] = "obj_relic_yottabyte_processor";
global.__objectNames[605] = "obj_relic_pineapple2";
global.__objectNames[606] = "obj_shop_yottabyte3";
global.__objectNames[607] = "obj_relic_midnight_meal";
global.__objectNames[608] = "obj_relic_pineapple_pudding";
global.__objectNames[609] = "obj_relic_morning_star";
global.__objectNames[610] = "obj_relic_rabbit_foot";
global.__objectNames[611] = "obj_relic_mega_quantum_chip";
global.__objectNames[612] = "obj_shop_submachinegun";
global.__objectNames[613] = "obj_relic_alcoholic1";
global.__objectNames[614] = "obj_relic_pineapple3";
global.__objectNames[615] = "obj_relic_alcoholic2";
global.__objectNames[616] = "obj_relic_infinity3";
global.__objectNames[617] = "obj_relic_midnight2";
global.__objectNames[618] = "obj_relic_watchful2";
global.__objectNames[619] = "obj_relic_watchful1";
global.__objectNames[620] = "obj_relic_watchful3";
global.__objectNames[621] = "obj_relic_midnight1";
global.__objectNames[622] = "obj_relic_midnight3";
global.__objectNames[623] = "obj_relic_crystal1";
global.__objectNames[624] = "obj_relic_alcoholic3";
global.__objectNames[625] = "obj_relic_crystal2";
global.__objectNames[626] = "obj_relic_crystal3";
global.__objectNames[627] = "obj_relic_infinity2";
global.__objectNames[628] = "obj_relic_dev2";
global.__objectNames[629] = "obj_relic_yottabyte2";
global.__objectNames[630] = "obj_revival_hologram";
global.__objectNames[631] = "obj_relic_yottabyte3";
global.__objectNames[632] = "obj_relic_infinity1";
global.__objectNames[633] = "obj_relic_yottabyte1";
global.__objectNames[634] = "obj_relic_dev3";
global.__objectNames[635] = "obj_relic_dev1";
global.__objectNames[636] = "obj_slot_tiered3";
global.__objectNames[637] = "obj_sae";
global.__objectNames[638] = "obj_slot_resource";
global.__objectNames[639] = "obj_hackTerminal1";
global.__objectNames[640] = "obj_slot_tiered1";
global.__objectNames[641] = "obj_slot_tiered2";
global.__objectNames[642] = "class_hack";
global.__objectNames[643] = "obj_gunnar";
global.__objectNames[644] = "obj_shopReset";
global.__objectNames[645] = "class_endShop_weapon";
global.__objectNames[646] = "obj_hackTerminal2";
global.__objectNames[647] = "class_endShop_relic";
global.__objectNames[648] = "class_endShop_ammo";
global.__objectNames[649] = "class_slot_tiered";
global.__objectNames[650] = "class_endshop_tiered";
global.__objectNames[651] = "class_endShop_resource";
global.__objectNames[652] = "obj_endShop_ammoLight";
global.__objectNames[653] = "obj_endShop_heavyShotgun";
global.__objectNames[654] = "obj_endShop_ammoGrenades";
global.__objectNames[655] = "obj_endShop_bouncerPistol";
global.__objectNames[656] = "obj_endShop_blitz";
global.__objectNames[657] = "obj_endShop_ammoHeavy";
global.__objectNames[658] = "obj_endShop_blastPistol";
global.__objectNames[659] = "obj_endShop_crudeAssaultRifle";
global.__objectNames[660] = "obj_endShop_assaultRifle";
global.__objectNames[661] = "obj_endShop_highmag";
global.__objectNames[662] = "obj_endShop_bouncer";
global.__objectNames[663] = "obj_endShop_health";
global.__objectNames[664] = "obj_endShop_flakCannon";
global.__objectNames[665] = "obj_endShop_kamilauncher";
global.__objectNames[666] = "obj_endShop_minigun";
global.__objectNames[667] = "obj_endShop_plasmaSMG";
global.__objectNames[668] = "obj_endShop_relicPistol";
global.__objectNames[669] = "obj_endShop_plasmaPistol";
global.__objectNames[670] = "obj_endShop_relicRifle";
global.__objectNames[671] = "obj_endShop_ammoMedium";
global.__objectNames[672] = "obj_endShop_relicMinigun";
global.__objectNames[673] = "obj_endShop_relicRocket";
global.__objectNames[674] = "obj_endShop_assaultPistol";
global.__objectNames[675] = "obj_endShop_relicSMG";
global.__objectNames[676] = "obj_endShop_rocketLauncher";
global.__objectNames[677] = "obj_endShop_relicShotgun";
global.__objectNames[678] = "obj_endShop_sawedoff";
global.__objectNames[679] = "obj_endShop_smg";
global.__objectNames[680] = "obj_endShop_shotgun";
global.__objectNames[681] = "obj_endShop_machinegun";
global.__objectNames[682] = "obj_endShop_overshield";
global.__objectNames[683] = "obj_endShop_sniperRifle";
global.__objectNames[684] = "obj_endShop_devPotion";
global.__objectNames[685] = "obj_endShop_crystalBacon";
global.__objectNames[686] = "obj_endShop_midnightBeer";
global.__objectNames[687] = "obj_endShop_infinityBattery";
global.__objectNames[688] = "obj_endShop_heavyPistol";
global.__objectNames[689] = "obj_endShop_pineapplePudding";
global.__objectNames[690] = "obj_endShop_rabbitFoot";
global.__objectNames[691] = "obj_endShop_watchfulEye";
global.__objectNames[692] = "obj_endShop_yottabyteDrive";
global.__objectNames[693] = "obj_endShop_yottabyteProcessor";
global.__objectNames[694] = "obj_endShop_relicCannon";
global.__objectNames[695] = "obj_endShop_relicSniper";
global.__objectNames[696] = "fx_chestRegular";
global.__objectNames[697] = "obj_endShop_alcoholicCarrot";
global.__objectNames[698] = "obj_endShop_midnightMeal";
global.__objectNames[699] = "class_treasureChest";
global.__objectNames[700] = "fx_chestDucan";
global.__objectNames[701] = "obj_endShop_morningStar";
global.__objectNames[702] = "fx_chestHaunted";
global.__objectNames[703] = "obj_endShop_megaQuantumChip";
global.__objectNames[704] = "obj_endShop_pineapplePie";
global.__objectNames[705] = "obj_chestRegular";
global.__objectNames[706] = "obj_chestDucan";
global.__objectNames[707] = "obj_chestHaunted";
global.__objectNames[708] = "class_chestFX";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for